### ISSUE TITLE
user profile page

### ISSUE THREAD

**Issue by gogson** [SylTi/bitfunding#16]
Adds a profiel page route : /users/name
User listing page is not needed.

**Comment by gogson** [comment]
## Profile page for users (github-like)

![screen shot 2014-11-13 at 19 09 04](https://cloud.githubusercontent.com/assets/3675776/5033723/a587d99e-6b68-11e4-8f4a-bb05b5130f7e.png)

Right now we're just showing basic user datas.

## Next step
- Show user projects
- Show user contributions list (per project) if anonymous mode is disabled.

**Comment by gogson** [comment]
what do we show when the user is in anonymous mode ?
"No contributions" OR "This user's contributions are not public" ?

**Comment by SylTi** [comment]
"This user's contributions are not public"
