### ISSUE TITLE
Project status in db

### ISSUE THREAD

**Issue by gogson** [SylTi/bitfunding#23]
Instead of deducing the project status, put an attribute in db.
Default status : "inactive"
- When a contribution happens :
  - if first contribution and project not finished > apply "ongoing" status
  - if (project end date > now) then apply "finished" status and contribution fails
- Admins can apply contributions only when project is "finished" i.e. project end date is finished.

**Comment by SylTi** [comment]
Don't use the attribute active already in for  ongoing, use something new like status.
It will be used for projectenddate 

Not sure what you mean by "Admins can apply contributions only when project is "finished" "

take a look at #24

**Comment by SylTi** [comment]
The other problem with that is that we have 5 status and some of them depend on the date of the day not only the amount contributed, so where are we supposed to update them ? No cron obv

or we could just code some helpers like isOngoing() isFinished()

**Comment by gogson** [comment]
Ok for the helpers solution.
We'll need one for client and one for server ? (the same but for both sides)

**Comment by SylTi** [comment]
Yeah that's the all point of using JS on both side, we can share the code :smile:
