### ISSUE TITLE
Project page 

### ISSUE THREAD

**Issue by SylTi** [SylTi/bitfunding#34]
There is two bug in the page.
- When we delete an account who got a project, and then go to that project page; project page appears empty.
  Should we return funds and delete the project when a user is deleted?
- When a project dateEndCampaign is set to the same month : "Project started 7 minutes ago and finishing 45 years ago"

**Comment by gogson** [comment]
Do we really want to be able to delete users ?
Why not just "disabling" them : they can't log anymore.

If we want to delete users, we should delete their projects and contributions too.

**Comment by SylTi** [comment]
I think that could be better too. Because we need to refund is balance.
But what do we do when a user a deactivated ? Do we deactivate is project(s) ? What about is contribution ? Refund or let them ?

The easiest would probably be : 
- Deactivate project(s)
- Refunds user who contributed
- Let is contributions stay
