### ISSUE TITLE
Please delete comment.

### ISSUE THREAD

**Issue by earlyraven** [SylTi/bitfunding#64]
Hi, my account was compromised and the attacker left a bad comment.  I've just regained access.  I tried to remove it, but the thread is locked.  Can you please delete the comment that was posted here?  https://github.com/SylTi/bitfunding/issues/50#issuecomment-1865282150

Also, if you know of a way to search for all such comments and delete them, I would appreciate that.  Sorry for any inconvenience.

Thanks.

**Comment by gogson** [comment]
done
